name: Build and Deploy...
on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 16.20.0
      - name: Install dependencies
        run: yarn 
 
      - name: Build application
        run: |
          yarn build
          pwd
          ls
          # yarn generate
      - name: Deploy on server
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.DEV_HOST }}
          username: ${{ secrets.DEV_USERNAME }}
          password: ${{ secrets.DEV_PASSWORD }}
          source: "/home/runner/work/core-client/core-client/dist"
          target: ${{ secrets.DEV_PATH }}